NumberTwoLabs/NumberTwoLabs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pooperRater import views
from django.views.generic import RedirectView





urlpatterns = patterns('',

    url(r'^$', 'pooperRater.views.places', name='places'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.home_page, name='index'),


    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'successful_logout'}, name='logout'),
    url(r'^successful_logout/$', 'pooperRater.views.successful_logout', name='successful_logout'),
    url(r'^login_redirect/$', 'pooperRater.views.login_redirect', name='login_redirect'),
    url('', include('django.contrib.auth.urls', namespace='auth')),


    url(r'^api/v1/', include('pooperRater.api.urls')),
    url(r'^yelp/ajax/$', views.yelp_ajax, name='yelp_ajax'),
    url(r'^profile', views.profile, name='profile'),
)

NumberTwoLabs/pooperRater/api/urls.py
from django.conf.urls import patterns, include, url
from pooperRater.api.views import RatingViewSet, PlaceViewSet, UserViewSet, AnonUserInfoViewSet, VoteViewSet, PlaceRatingViewSet, RatingOwnerViewSet, PlaceSearchViewSet
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'ratings', RatingViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'place_search',PlaceSearchViewSet)
router.register(r'vote', VoteViewSet)
router.register(r'user', UserViewSet)
router.register(r'anon', AnonUserInfoViewSet)

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^places/(?P<pk>[0-9]+)/ratings/$', PlaceRatingViewSet.as_view()),
    url(r'^ratings/(?P<pk>[0-9]+)/owner/$', RatingOwnerViewSet.as_view()),
)

NumberTwoLabs/pooperRater/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg


class Place(models.Model):
    # PlaceListItem data - general
    name = models.CharField(max_length=80)
    address = models.CharField(null=True, blank=True, max_length=120)
    city = models.CharField(null=True, blank=True, max_length=120)
    desc = models.TextField(null=True, blank=True, max_length=200)

    # Location data
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    # PlaceListItem data specific to yelp
    yelp_id = models.CharField(max_length=100, null=True, blank=True, unique=True)
    yelp_url = models.URLField(null=True, blank=True)
    yelp_categories = models.TextField(blank=True)


    # PlaceListItem data specific to google
    google_id = models.CharField(max_length=100, null=True, blank=True)

    type_conversion = {
        1: "placeholder",
        2: "bad food",
        3: "new string"
    }

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def number_of_ratings(self):
        return Rating.objects.filter(place__id=self.id).count()

    @property
    def average_rating(self):
        empty_list = {}

        if Rating.objects.filter(place__id=self.id).aggregate(Avg('air_flow')) > 0:
            empty_list.update(Rating.objects.filter(place__id=self.id).aggregate(Avg('air_flow')))

        if Rating.objects.filter(place__id=self.id).aggregate(Avg('cleanliness')) > 0:
            empty_list.update(Rating.objects.filter(place__id=self.id).aggregate(Avg('cleanliness')))

        if Rating.objects.filter(place__id=self.id).aggregate(Avg('available')) > 0:
            empty_list.update(Rating.objects.filter(place__id=self.id).aggregate(Avg('available')))

        if Rating.objects.filter(place__id=self.id).aggregate(Avg('quality')) > 0:
            empty_list.update(Rating.objects.filter(place__id=self.id).aggregate(Avg('quality')))

        if Rating.objects.filter(place__id=self.id).aggregate(Avg('other')) > 0:
            empty_list.update(Rating.objects.filter(place__id=self.id).aggregate(Avg('other')))

        return empty_list


    @property
    def overall_average_rating(self):
        overall_average = 0

        for average in self.average_rating:
            if self.average_rating[average] != None:
                overall_average += self.average_rating[average]
        return overall_average / len(self.average_rating)

    def __unicode__(self):
        return u"{}".format(self.name)


class AnonUserInfo(models.Model):
    related_user = models.OneToOneField(User, related_name='anon_user')
    anonymous_name = models.CharField(max_length=80, default='Anonymous', unique=True)
    user_img = models.ImageField(null=True, blank=True)

    def __unicode__(self):
        return u"{}".format(self.anonymous_name)


class Rating(models.Model):
    # links
    owner = models.ForeignKey(User)
    place = models.ForeignKey(Place)

    # Stars
    STAR_CONVERSION = (
        (1, 'One'),
        (2, 'Two'),
        (3, 'Three'),
        (4, 'Four'),
        (5, 'Five'),
    )
    air_flow = models.PositiveSmallIntegerField(choices=STAR_CONVERSION)
    cleanliness = models.PositiveSmallIntegerField(choices=STAR_CONVERSION)
    available = models.PositiveSmallIntegerField(choices=STAR_CONVERSION)
    quality = models.PositiveSmallIntegerField(choices=STAR_CONVERSION)
    other = models.PositiveSmallIntegerField(choices=STAR_CONVERSION)

    rating_comment = models.TextField(null=True, blank=True, max_length=1000)

    # user_rated = models.CommaSeparatedIntegerField(max_length=500, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, **kwargs):
        super(Rating, self).save(**kwargs)
        vote = Vote(rating_vote=self)
        vote.save()

    # @property
    # def users_rated_ratings(self):
    #     user_rated = []
    #     owners = Vote.objects.filter(rating_vote__id = self.id).values('vote_owner')
    #     for item in owners:
    #         user_rated.append(item['vote_owner'])
    #     return user_rated

    @property
    def number_of_upvotes(self):
        return Vote.objects.filter(rating_vote__id=self.id).filter(upvote=True).count()

    @property
    def number_of_downvotes(self):
        return Vote.objects.filter(rating_vote__id=self.id).filter(downvote=True).count()

    def __unicode__(self):
        return u"{}, {}".format(self.place, self.owner)


class Vote(models.Model):
    # vote_owner = models.ForeignKey(User)
    rating_vote = models.ForeignKey(Rating)
    upvote = models.BooleanField(default=False)
    downvote = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"{}".format(self.rating_vote)

NumberTwoLabs/pooperRater/forms.py
from django import forms
from pooperRater.models import AnonUserInfo, Place


class AnonUserInfoCreationForm(forms.ModelForm):
    class Meta:
        model = AnonUserInfo
        fields = ('anonymous_name',)
        labels = {'anonymous_name': 'Anonymous Name'}

class ManualPlaceCreationForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ('name', 'address', 'city',)
        help_texts = {
            'name': 'The following fields are optional.',
        }

NumberTwoLabs/pooperRater/api/views.py
from django.contrib.auth.models import User
from rest_framework import viewsets, generics, filters
from pooperRater.models import Rating, Place, User, AnonUserInfo, Vote
from pooperRater.api.serializer import RatingSerializer, PlaceSerializer, UserSerializer, AnonUserInfoSerializer, VoteSerializer
from pooperRater.permissions import IsOwnerOrReadOnly, IsAdminUserOrReadOnly, AnonInfoIsRelatedUserOrReadOnly, UserIsOwnerOrReadOnly, VoteIsOwnerOrReadOnly
from rest_framework import permissions


class RatingViewSet(viewsets.ModelViewSet):
    queryset = Rating.objects.all()
    serializer_class = RatingSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)


class PlaceRatingViewSet(generics.ListCreateAPIView):
    serializer_class = RatingSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)

    def get_queryset(self, *args, **kwargs):
        return Rating.objects.filter(place__id=self.kwargs.get('pk'))


class RatingOwnerViewSet(generics.ListCreateAPIView):
    serializer_class = AnonUserInfoSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, AnonInfoIsRelatedUserOrReadOnly,)

    def get_queryset(self, *args, **kwargs):
        u = User.objects.get(rating__id=self.kwargs.get('pk'))
        return AnonUserInfo.objects.filter(related_user=u)


class PlaceViewSet(viewsets.ModelViewSet):
    queryset = Place.objects.all()
    serializer_class = PlaceSerializer
    permission_classes = ()
    filter_backends = (filters.SearchFilter,)
    search_fields = ('yelp_id',)
    # permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsAdminUserOrReadOnly,)

class PlaceSearchViewSet(viewsets.ModelViewSet):
    queryset = Place.objects.all()
    serializer_class = PlaceSerializer
    permission_classes = ()
    filter_backends = (filters.SearchFilter,)
    search_fields = ('name', 'address', 'city',)

class VoteViewSet(viewsets.ModelViewSet):
    queryset = Vote.objects.all()
    serializer_class = VoteSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, VoteIsOwnerOrReadOnly,)

# class RatingsVoteViewSet(viewsets.ModelViewSet):
#     serializer_class = VoteSerializer
#
#     def get_queryset(self, *args, **kwarg):
#         return Rating.object.get(rating__id=self.kwargs.get('pk'))
#
#     def create(self, request, *args, **kwargs):
#         serializer = self.get_serializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         self.perform_create(serializer)
#         headers = self.get_success_headers(serializer.data)
#         return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, UserIsOwnerOrReadOnly,)


class AnonUserInfoViewSet(viewsets.ModelViewSet):
    queryset = AnonUserInfo.objects.all()
    serializer_class = AnonUserInfoSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, AnonInfoIsRelatedUserOrReadOnly,)
    filter_backends = (filters.SearchFilter,)
    search_fields = ('=anonymous_name',)

NumberTwoLabs/pooperRater/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError
from pooperRater.api_calls import yelp_business_search
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from pooperRater.forms import AnonUserInfoCreationForm, ManualPlaceCreationForm
from pooperRater.models import AnonUserInfo


def places(request):
   context = RequestContext(request,
                           {'user': request.user})
   return render_to_response('places/places.html', context_instance=context)

def place(request):
   context = RequestContext(request,
                           {'user': request.user})
   return render_to_response('places/place.html', context_instance=context)

def home_page(request):
    context = RequestContext(request, {'user': request.user})
    return render_to_response('places/places.html', context_instance=context)

def successful_logout(request):
    return render(request, 'registration/successful_logout.html')

def yelp_ajax(request):
    data={}
    # If user makes a search
    if request.method == "GET":
        term=request.GET['term']
        data['term'] = term

        # If user inputs an address
        # Checks whether location was input
        try:
            location = request.GET["location"]
            data['location']=location
            # Makes the api call to yelp
            yelp_response = yelp_business_search.main(term, location)
        # If user is searching by automatically generated geolocation instead
        except MultiValueDictKeyError:
            geoCoordLat = float(request.GET["geoCoordLat"])
            geoCoordLong = float(request.GET["geoCoordLong"])
            yelp_response = yelp_business_search.main(term, (geoCoordLat, geoCoordLong))

        data['yelp'] = yelp_response # Unused, but helpful for debugging
        businesses = yelp_response['businesses']
        # data['businesses'] = json.loads(businesses)
    return JsonResponse(businesses, safe=False, status=200)

def profile(request):
    data = {}

    # For first time users only
    first_login_time = str(request.user.date_joined)[:18]
    last_login_time = str(request.user.last_login)[:18]
    if first_login_time == last_login_time:
        data['welcome_message'] = "Since this is your first login, please select an unidentifiable anonymous username that will be viewed with your ratings"

    if request.method == "POST":
        has_anon = AnonUserInfo.objects.filter(related_user=request.user)
        if has_anon:
            form = AnonUserInfoCreationForm(request.POST, instance=has_anon[0])
        # Want to force uniqueness: each user can only have one anon
        else:
            form = AnonUserInfoCreationForm(request.POST)
        # Creates anon user object, but doesn't save to database
        new_anon_user = form.save(commit=False)
        # Sets related user to whoever is signed in
        new_anon_user.related_user = request.user
        new_anon_user.save()
        return redirect('index')

    # If method is not post
    # Get will error out if no anon user, so use filter and return the first
    has_anon = AnonUserInfo.objects.filter(related_user=request.user)
    if has_anon:
        form = AnonUserInfoCreationForm(instance=has_anon[0])
    else:
        form = AnonUserInfoCreationForm({'anonymous_name': "Anonymous"+str(request.user.id)})
    data['form'] = form
    return render(request, 'registration/profile.html', data)

def login_redirect(request):
    # To check if first time login, compare the first and last login
    first_login_time = str(request.user.date_joined)[:18]
    last_login_time = str(request.user.last_login)[:18]
    if first_login_time == last_login_time:
        return redirect('/profile/')
    else:
        return redirect('/#')
########################## user profiles ##########################
# @login_required
# def profile(request):
#     user_social_auth = request.user.social_auth.filter(provider='facebook').first()
#     graph = facebook.GraphAPI(user_social_auth.extra_data['access_token'])
#     profile_data = graph.get_object("me")
#     return render(request, 'profile.html', profile_data)
######################### user rest api view #######################

NumberTwoLabs/pooperRater/templates/boostrap_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test page</title>

    <!-- Bootstrap -->
    <link href="../static/src/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="../static/src/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>

NumberTwoLabs/pooperRater/templates/footer.html
<footer class="footer">
      <div class="panel-footer">
                <p class="text-muted">Place sticky footer content here.</p>
      </div>
</footer>

NumberTwoLabs/pooperRater/templates/google_places_snippet.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>Place 1km around you</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" charset="utf-8">
    <link href="../static/css/google_places.css" type="text/css" rel="stylesheet">
  </head>
  <body>
  <div id="title">
      <h3>Places 1km around you</h3>
  </div>
    <div id="map-canvas"></div>

  <div id="place-details"><span style="font-weight:bold;">Place Details</span></div>


  <footer id="end">
      <p>Copyright Number 2 Labs</p>
  </footer>

  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
  <script src= "{% static 'js/google_places.js' %}"></script>
  </body>
</html>

NumberTwoLabs/pooperRater/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>PoopeRater by #2 Labs</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript">
    if (window.location.hash && window.location.hash == '#_=_') {
        window.location.hash = '#';
    }
  </script>
  {% include 'stylesheet.html' %}

</head>

<body style="width: 100%; height: 100%; background-color:rgb(226, 226, 226)">
  {% include 'navbar.html' %}

    <div class="top">
      <div class="container-fluid">
            <div class="innerAlignment">
                {% block content2 %}{% endblock content2 %}
            </div>
      </div>
    </div>

    <br>
    <br>
    <br>

    <div id="footer">
        <div class="container-fluid">
            <div class="row">
                <div style="margin-left:50px;">Made with <span class="fa fa-heart" style="color: crimson;"></span> by <a href="http://www.numbertwolabs.com" target="_blank">NumberTwoLabs.com</a></div>
            </div>
        </div>
    </div>


  {% include 'javascript.html' %}
</body>
</html>

NumberTwoLabs/pooperRater/templates/javascript.html
{% load staticfiles %}

<!--Note: we should only include libraries we need on each page, rather than importing them all
on every page.
Don't use minified react. It breaks the routes-->

<script src="{% static 'src/jquery-2.1.3.min.js' %}"></script>
<script src="{% static 'src/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'src/react/react.js' %}"></script>
<script src="{% static 'src/react/JSXTransformer.js' %}"></script>
<script src="{% static 'src/Showdown.min.js' %}"></script>
<script src="{% static 'src/bootstrap/js/bootstrap.min.js' %}"></script>

<script type="text/jsx;harmony=true" src="{% static 'js/infinite-scroll.js' %}"></script>

<script type="text/jsx;harmony=true" src="{% static 'js/uniqueUsernameCheck.js' %}"></script>

<script type="text/jsx;harmony=true" src="{% static 'js/place_map.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/places.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/place.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/ratings.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/vote.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/postRatings.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/user_info.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/add_rating_button.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/back_button.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/add_place_button.js' %}"></script>

<!-- user ID -->
{% if user.id %}
<script>GlobalUserID = {{ user.id }}</script>
{% else %}
<script>GlobalUserID = 0</script>
{% endif %}
<script>
    if (GlobalUserID === 0) {
        document.getElementById("loggedInWarning").className = "alert alert-info";
    }
</script>

<script type="text/jsx;harmony=true" src="{% static 'js/button_control.js' %}"></script>
<script type="text/jsx;harmony=true" src="{% static 'js/app.js' %}"></script>


<script src="{% static 'js/router.js' %}"></script>

NumberTwoLabs/pooperRater/templates/modals.html
<!-- Modal -->
<div class="modal fade" id="addPlaceModal" tabindex="-1" role="dialog" aria-labelledby="addPlaceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title text-center" id="addPlaceModalLabel">Add a Business Manually</h3>
            </div>
            <div class="modal-body">
                <form method="POST">
                    <div class="text-left">
                        <label>Business name <small>*Required</small></label><br>
                        <input type="text" class="form-control" id ="placeName" placeholder="Number Two Labs"><br>
                        <ul id="nameRequired" style="display:none"><li>This business needs a name!</li></ul>
                        <label>Address</label><br>
                        <input type="text" class="form-control" id="placeAddress" placeholder="1234 Sesame Street"><br>
                        <label>City</label><br>
                        <input type="text" class="form-control" id="placeCity" placeholder="San Francisco"><br>
                        <div id="manualResult"></div>
                    </div>

                    <div class ="modal-footer">
                        <button type="button" class="btn btn-warning" onclick="addPlaceToDatabase()">Add place</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <!--<button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal" data-target="#newModal">Now rate it!</button>-->
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

<!--Yelp modal-->
<div class="modal fade" id="yelpModal" tabindex="-1" role="dialog" aria-labelledby="yelpModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color: #fafafa">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" id="yelpModalLabel">Add a Place from Yelp</h3>
            </div>
            <div class="modal-body text-center">
                <script src="../static/src/jquery-1.11.2.min.js"></script>
                <script src="../static/js/ajax.js"></script>

                <!--<h3>Add a place from Yelp</h3>-->
                <div class="btn-group">
                    <!--Change value of yelpIsLocation to determine type of search-->
                    <button type="button" id="yelpIsNear" class="active btn btn-default" name="inputAddress" value="yes" onclick="document.getElementById('yelpIsLocation').value='no';returnUserPosition();"><b>Nearby Places</b></button>
                    <button type="button" id="yelpIsLocation" class="btn btn-default" name="inputAddress" value="no" onclick="this.value='yes';enableLocationSearch();"><b>Search by address</b></button><br>
                </div>

                <div id="userCoord" style="display:block;">
                    <p><small id="placeholderWhileGettingLocation"></small></p>
                    <p><span id="userLat" style="display:none;"></span>
                    <span id="userLong" style="display:none;"></span></p>
                </div>

                <form id="ajaxForm">
{#                    {% csrf_token %}#}
                    <!--User provided location-->
                    <div class="col-lg-6 col-lg-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
                        <input type="text" class="form-control" placeholder="E.g. 200 California St" id="ajaxLocation"><br>
                        <input type="text" class="form-control" placeholder="E.g. dinner" id="ajaxTerm">
                    </div>
                    <!--Coordinates stay hidden-->
                    <input id="yelpGeoCoordLat" type="text" style="display:inline-block;visibility:hidden;">
                    <input id="yelpGeoCoordLong" type="text" style="display:inline-block;visibility:hidden;">
                </form>
                <br>
                <div class="col-lg-12">
                    <button type="button" class="btn btn-danger btn-lg" onclick="yelp_ajax();">Search on Yelp!</button>&nbsp;
                </div>
                <p></p>
                <br>
                <br>
                <div id="yelpOutput"></div>

                <script src="../static/js/yelp_search.js"></script>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal" data-toggle="modal" data-target="#addPlaceModal">Can't find it? Add manually!</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!--DELETE-->
     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!--<script src="../static/src/bootstrap/js/bootstrap.min.js"></script>-->

NumberTwoLabs/pooperRater/templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#togglebar">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#"><div><img width="27px" height="27px" src="../static/img/Logo.png"/><span style="font-size:1.2em;position:absolute;color:#E2E2E2;">Poope<span style="color:#F0AD4E">Rater</span></span></div></a>
    </div>

    <div class="collapse navbar-collapse" id="togglebar">
      <ul class="nav navbar-nav pull-right">
        {% if user.is_authenticated %}
          <li><a href="/profile/">{{ user.username }}</a></li>
          <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
        {% else %}
          <li><a href="/login">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

NumberTwoLabs/pooperRater/templates/stylesheet.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'src/bootstrap/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'src/bootstrap/css/font-awesome.css' %}" />
<link rel="stylesheet" href="{% static 'css/stylesheet.css' %}" />
<link rel="stylesheet" href="{% static 'css/google_places.css' %}" />